name: carnd-term1-2019
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python>=3.6
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - pyqt
    - moviepy
    - requests
    - keras
    - pip:
        - opencv-python
        - tf-nightly-gpu
