name: CarND-Term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - pip:
        - moviepy
        - keras
